# Generated by Django 4.1.2 on 2022-12-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.kategori'),
        ),
    ]
