# Generated by Django 4.1.2 on 2022-12-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_altkategori_urun_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
